name: "NoLongerEvil HomeAssistant"
description: "NoLongerEvil Nest API"
version: "0.0.1"
slug: "nolongerevil"
init: false
ingress: true
ingress_port: 8081
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8081/tcp: 8081
  80/tcp: 8000
