---
name: "NoLongerEvil HomeAssistant"
description: "NoLongerEvil Nest API - Self-hosted Nest thermostat control"
version: "0.0.2"
slug: "nolongerevil"
init: false
ingress: true
ingress_port: 8081
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  8081/tcp: 8081
  80/tcp: 8000
ports_description:
  8081/tcp: "Control API (web interface)"
  80/tcp: "Proxy port (Nest device communication)"
map:
  - addon_config
